name: devtools
version: 1.0.0
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: DirectCode Development Tools
homepage: https://github.com/DirectMyFile/devtools
environment:
  sdk: '>=1.6.0-dev'
dependencies:
  args: '>=0.12.0 <0.15.0'
  collection: '>=0.9.4 <0.10.0'
  crypto: '>=0.9.0 <1.0.0'
  github: '>=0.5.9 <0.6.0'
  http: '>=0.11.1+1 <0.15.0'
  logging: '>=0.9.2 <0.10.0'
  path: '>=1.3.0 <2.0.0'
  quiver: '>=0.18.2 <0.19.0'
  yaml: '>=2.0.0 <2.2.0'
dev_dependencies:
  hop: '>=0.31.0+1 <0.32.0'
  unittest: '>=0.11.0+4 <0.12.0'
dependency_overrides:
  args: '>=0.12.0 <0.15.0'
