name: devtools
version: 1.0.0
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: DirectCode Development Tools
homepage: https://github.com/DirectMyFile/devtools
environment:
  sdk: '>=1.6.0-dev'
dependencies:
  ansicolor: '>=0.0.9 <0.1.0'
  args: '>=0.11.0+1 <0.15.0'
  http: '>=0.11.1+1 <0.15.0'
  path: '>=1.2.2 <2.0.0'
  yaml: '>=2.0.0 <2.2.0'
